final List<String> governoratesList = [
  'erbil',
  'al-anbar',
  'babil',
  'baghdad',
  'basra',
  'duhok',
  'al-qadisiyah',
  'dialah',
  'dhi qar',
  'al-sulaymaniyah',
  'salah al-deen',
  'karkuk',
  'karbalaa',
  'al-muthanna',
  'misan',
  'al-najaf',
  'naynawah',
  'wasit',
];

final Map<String, String> governoratesNamesMapEnglish = {
  'erbil': '1',
  'al-anbar': '2',
  'babil': '3',
  'baghdad': '4',
  'basra': '5',
  'duhok': '6',
  'al-qadisiyah': '7',
  'dialah': '8',
  'dhi qar': '9',
  'al-sulaymaniyah': '10',
  'salah al-deen': '11',
  'karkuk': '12',
  'karbalaa': '13',
  'al-muthanna': '14',
  'misan': '15',
  'al-najaf': '16',
  'naynawah': '17',
  'wasit': '18',
};

final Map<String, String> governoratesNamesMapArabic = {
  'أربيل': '1',
  'الأنبار': '2',
  'بابل': '3',
  'بغداد': '4',
  'البصرة': '5',
  'دهوك': '6',
  'القادسية': '7',
  'ديالى': '8',
  'ذي قار': '9',
  'السليمانية': '10',
  'صلاح الدين': '11',
  'كركوك': '12',
  'كربلاء': '13',
  'المثنى': '14',
  'ميسان': '15',
  'النجف': '16',
  'نينوى': '17',
  'واسط': '18',
};

final Map<String, String> governoratesNumbersMap = {
  '1': 'erbil',
  '2': 'al-anbar',
  '3': 'babil',
  '4': 'baghdad',
  '5': 'basra',
  '6': 'duhok',
  '7': 'al-qadisiyah',
  '8': 'dialah',
  '9': 'dhi qar',
  '10': 'al-sulaymaniyah',
  '11': 'salah al-deen',
  '12': 'karkuk',
  '13': 'karbalaa',
  '14': 'al-muthanna',
  '15': 'misan',
  '16': 'al-najaf',
  '17': 'naynawah',
  '18': 'wasit',
};

// "Erbil": "erbil",
// "Al-Anbar": "al-anbar",
// "Babil": "babil",
// "Baghdad": "baghdad",
// "Basra": "basra",
// "Duhok": "duhok",
// "Al-Qadisiyah": "al-qadisiyah",
// "Dialah": "dialah",
// "Dhi Qar": "dhi qar",
// "Al-Sulaymaniyah": "al-sulaymaniyah",
// "Salah Al-Deen": "salah al-deen",
// "Karkuk": "karkuk",
// "Karbalaa": "karbalaa",
// "Al-Muthanna": "al-muthanna",
// "Misan": "misan",
// "Al-Najaf": "al-najaf",
// "Naynawah": "naynawah",
// "Wasit": "wasit"

// "أربيل": "erbil",
// "الأنبار": "al-anbar",
// "بابل": "babil",
// "بغداد": "baghdad",
// "البصرة": "basra",
// "دهوك": "duhok",
// "القادسية": "al-qadisiyah",
// "ديالى": "dialah",
// "ذي قار": "dhi qar",
// "السليمانية": "al-sulaymaniyah",
// "صلاح الدين": "salah al-deen",
// "كركوك": "karkuk",
// "كربلاء": "karbalaa",
// "المثنى": "al-muthanna",
// "ميسان": "misan",
// "النجف": "al-najaf",
// "نينوى": "naynawah",
// "واسط": "wasit"
